# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: Bash@3
  displayName: Install MAUI
  inputs:
    targetType: 'inline'
    script: |
      dotnet nuget locals all --clear 
      dotnet workload install maui
      dotnet workload install android ios maui wasm-tools

- task: Bash@3
  displayName: Restore nuget
  inputs:
    targetType: 'inline'
    script: |
        cd src/
        dotnet restore QuickStockTaker.sln

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/QuickStockTaker.sln'
    arguments: '-c Release -f net8.0-android'
